### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by locnguyen** [fb55/SimpleQueue#4]
This library is getting highlighted as problematic by a security scan. it needs a license file and updated  package.json file too.

**Comment by locnguyen** [comment]
I opened PR #5 to fix this issue. Please review, merge, and bump the package version to publish the changes on npm. Thanks!

**Comment by locnguyen** [comment]
Thank you for merging my PR ❤️ Can you publish to npm when you get the chance? It still has 0.0.1 on there: https://www.npmjs.com/package/SimpleQueue

**Comment by fzaninotto** [comment]
👍 please publish the updated version with license to npm, my license checking tools marks your lib as unlicenced.

**Comment by fb55** [comment]
Sorry for the delay, a `1.0.0` release is now out.
